syntax on   " the color highlighting.

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'tpope/vim-sensible'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'davidhalter/jedi-vim'
Plug 'Shougo/unite.vim'
Plug 'Shougo/vimfiler.vim'
Plug 'kien/rainbow_parentheses.vim'
Plug 'scrooloose/nerdtree'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" my customer config
set nu  " show line number
set cursorline  " point current line

set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4

set magic

" the brackets match and highlight {} | () | [] etc.
set showmatch

" use F3 to open the nerdtree
nnoremap <F3> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif